### ISSUE TITLE
problem with changed username

### ISSUE THREAD

**Issue by z3dd1cu55** [nuehm-arno/axolotl-mobian-installer#1]
When creating the Desktop Entry, you give the explicit path for the default username ('mobian').
As I  changed the username, the application isn't located at that path in my case.
Script doesn't give an error for this. I still got the 'congrats' message but the Desktop entry wasn't there.

Maybe you can either put a notice in the README.md to change the path in the script or ask for the username in the script or make the path with '~/' instead of the explicit path (if that's possible).

btw: thanks for making the script! It's super easy to install axolotl with it :)

**Comment by nuehm-arno** [comment]
Thanks for the feedback - this is indeed a good point.

**Comment by nuehm-arno** [comment]
is changed in v1.4

thanks!
